### ISSUE TITLE
Where is the lib folder of spark-bench?

### ISSUE THREAD

**Issue by akasaki** [ecurtin/spark-bench-custom-workload#1]
Hello,

Regarding to the step 4 of the instruction: "4. Move this new jar into the lib folder of your spark-bench installation", I can't find lib folder of my spark-bench. Here are all the folders I have got.

![image](https://user-images.githubusercontent.com/10787105/34471042-ea8cbc6a-ef0b-11e7-972b-fe9769e06e09.png)

Moreover, is it possible to have a more detailed tutorial regarding to adding a new workload? I am more interested in how to add a machine learning workload. Thanks.

**Comment by ecurtin** [comment]
Hi @akasaki, thanks for using Spark-Bench!

The `lib` folder is present in the _distribution_ of Spark-Bench. What you have is a clone of the repo. You can get a distribution from the Spark-Bench releases page as a tarball, or you can create one from the clone of the repo you have by running `sbt dist` which will create the distribution as a new folder within the repo. Also a handy command, `sbt rmDist` cleans up any distribution files.

You may be able to use your custom workload jar from the repo itself without creating a distribution, though this is something I have not experimented with. You could try placing your jar in the target files with the other jars created from `sbt assembly` or there may be other ways to do it. However, the more surefire way to go is to use the distribution folder with the `lib` directory already in place.

There's a tutorial covering custom workloads at our documentation site here: https://sparktc.github.io/spark-bench/developers-guide/custom-workloads/

And there are more that document how to contribute to the actual Spark-Bench codebase here: https://sparktc.github.io/spark-bench/developers-guide/
